# Generated by Django 5.2.10 on 2026-01-11 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompletenessType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Completeness Type',
                'verbose_name_plural': 'Completeness Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Determinative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Determinative',
                'verbose_name_plural': 'Determinatives',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Milieu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Milieu',
                'verbose_name_plural': 'Milieus',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NameType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Name Type',
                'verbose_name_plural': 'Name Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PublicationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Publication Type',
                'verbose_name_plural': 'Publication Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Series',
                'verbose_name_plural': 'Series',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WritingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Writing Type',
                'verbose_name_plural': 'Writing Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_id', models.IntegerField(help_text='Original Name_ID from the Excel file', unique=True)),
                ('name', models.CharField(db_index=True, help_text='The attested name', max_length=500)),
                ('variant_forms', models.TextField(blank=True, help_text='Variant spellings of the name', null=True)),
                ('correspondence', models.TextField(blank=True, help_text='Corresponding names in other traditions', null=True)),
                ('literature', models.TextField(blank=True, help_text='Bibliography references', null=True)),
                ('query', models.CharField(blank=True, db_index=True, help_text='Normalized version for searching', max_length=500, null=True)),
                ('uncertain', models.BooleanField(default=False, help_text='Whether this name is uncertain')),
                ('completeness', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='names', to='namefinder.completenesstype')),
                ('determinatives', models.ManyToManyField(blank=True, help_text='Determinatives used with this name', related_name='names', to='namefinder.determinative')),
                ('milieu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='names', to='namefinder.milieu')),
                ('name_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='names', to='namefinder.nametype')),
                ('writing_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='names', to='namefinder.writingtype')),
            ],
            options={
                'verbose_name': 'Name',
                'verbose_name_plural': 'Names',
                'ordering': ['query', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Fragment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_id', models.IntegerField(help_text='Original Fragment_ID from the Excel file', unique=True)),
                ('fragment_number', models.CharField(help_text="Fragment number within series (e.g., '51.108')", max_length=100)),
                ('series_fragment', models.CharField(db_index=True, help_text="Combined series + fragment (e.g., 'KBo 51.108')", max_length=200)),
                ('publication_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fragments', to='namefinder.publicationtype')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fragments', to='namefinder.series')),
            ],
            options={
                'verbose_name': 'Fragment',
                'verbose_name_plural': 'Fragments',
                'ordering': ['series__name', 'fragment_number'],
                'unique_together': {('series', 'fragment_number')},
            },
        ),
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_id', models.IntegerField(help_text='Original Instance_ID from the Excel file', unique=True)),
                ('title_epithet', models.TextField(blank=True, help_text='Title or epithet of the name', null=True)),
                ('spelling', models.TextField(blank=True, help_text='How the name is spelled in this instance', null=True)),
                ('line', models.CharField(blank=True, help_text='Line reference in the fragment', max_length=200, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes', null=True)),
                ('completeness', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='namefinder.completenesstype')),
                ('determinative', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='namefinder.determinative')),
                ('fragment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='namefinder.fragment')),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='namefinder.name')),
                ('instance_type', models.ForeignKey(blank=True, help_text='Type: place, deity, person', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='namefinder.nametype')),
                ('writing_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='namefinder.writingtype')),
            ],
            options={
                'verbose_name': 'Instance',
                'verbose_name_plural': 'Instances',
                'ordering': ['name__name', 'fragment__series_fragment'],
            },
        ),
    ]
