# Generated by Django 5.2.10 on 2026-01-11 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('namefinder', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fragment',
            unique_together=set(),
        ),
    ]
