# Generated by Django 5.2.10 on 2026-01-11 20:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namefinder', '0002_alter_fragment_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted')], max_length=10)),
                ('model_type', models.CharField(choices=[('name', 'Name'), ('fragment', 'Fragment'), ('instance', 'Attestation'), ('series', 'Series')], max_length=20)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('object_repr', models.CharField(help_text='String representation of the object', max_length=255)),
                ('old_data', models.JSONField(blank=True, help_text='Data before the change', null=True)),
                ('new_data', models.JSONField(blank=True, help_text='Data after the change', null=True)),
                ('change_summary', models.TextField(blank=True, help_text='Human-readable summary of changes')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('reverted', models.BooleanField(default=False)),
                ('reverted_at', models.DateTimeField(blank=True, null=True)),
                ('reverted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reverted_changes', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Change Log',
                'verbose_name_plural': 'Change Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
