# Generated by Django 5.2.10 on 2026-01-11 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namefinder', '0003_changelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fragment',
            name='original_id',
            field=models.IntegerField(blank=True, help_text='Original Fragment_ID from the Excel file (null for new records)', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='instance',
            name='original_id',
            field=models.IntegerField(blank=True, help_text='Original Instance_ID from the Excel file (null for new records)', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='name',
            name='original_id',
            field=models.IntegerField(blank=True, help_text='Original Name_ID from the Excel file (null for new records)', null=True, unique=True),
        ),
    ]
