# Generated by Django 5.2.10 on 2026-01-14 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namefinder', '0004_alter_fragment_original_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fragment',
            name='comments',
            field=models.TextField(blank=True, help_text='Additional comments or notes', null=True),
        ),
        migrations.AddField(
            model_name='fragment',
            name='cth',
            field=models.CharField(blank=True, help_text="CTH number (e.g., '530.53', '700')", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fragment',
            name='cth_description',
            field=models.TextField(blank=True, help_text='CTH description', null=True),
        ),
        migrations.AddField(
            model_name='fragment',
            name='cth_name',
            field=models.CharField(blank=True, help_text='CTH text name', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='fragment',
            name='date',
            field=models.CharField(blank=True, help_text="Date or period (e.g., 'jh', 'sjh', 'mh')", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fragment',
            name='date_uncertain',
            field=models.BooleanField(default=False, help_text='Whether the date is uncertain'),
        ),
        migrations.AddField(
            model_name='fragment',
            name='find_spot',
            field=models.TextField(blank=True, help_text='Archaeological find spot information', null=True),
        ),
        migrations.AddField(
            model_name='fragment',
            name='inventory_number',
            field=models.CharField(blank=True, help_text='Museum inventory number', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='fragment',
            name='is_matched',
            field=models.BooleanField(default=False, help_text='Whether this fragment was matched to CTH data'),
        ),
        migrations.AddField(
            model_name='fragment',
            name='match_method',
            field=models.CharField(blank=True, help_text='Method used to match this fragment', max_length=100, null=True),
        ),
    ]
