# Generated by Django 5.2.10 on 2026-03-08 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namefinder', '0005_add_fragment_cth_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='name',
            name='is_fragmentary',
            field=models.BooleanField(default=False, help_text='Whether this name is a fragmentary/incomplete reading (e.g. contains [ or …)'),
        ),
    ]
