# Generated by Django 5.2.10 on 2026-03-08 19:07

from django.db import migrations


def flag_fragmentary_names(apps, schema_editor):
    """Flag names containing [, ], ?, … or ending with - as fragmentary."""
    Name = apps.get_model('namefinder', 'Name')
    from django.db.models import Q
    updated = Name.objects.filter(
        Q(name__contains='[') | Q(name__contains=']') |
        Q(name__contains='…') | Q(name__contains='?') |
        Q(name__endswith='-') | Q(name__endswith='–') |
        Q(name__contains='x')
    ).update(is_fragmentary=True)
    print(f"\n  Flagged {updated} names as fragmentary")


def unflag_fragmentary_names(apps, schema_editor):
    """Reverse: unflag all fragmentary names."""
    Name = apps.get_model('namefinder', 'Name')
    Name.objects.filter(is_fragmentary=True).update(is_fragmentary=False)


class Migration(migrations.Migration):

    dependencies = [
        ('namefinder', '0006_add_is_fragmentary_to_name'),
    ]

    operations = [
        migrations.RunPython(flag_fragmentary_names, unflag_fragmentary_names),
    ]
