# Generated by Django 5.2.10 on 2026-03-08 22:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namefinder', '0007_flag_fragmentary_names'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('name', 'Name'), ('fragment', 'Fragment'), ('instance', 'Attestation')], max_length=20)),
                ('entry_id', models.PositiveIntegerField()),
                ('entry_repr', models.CharField(help_text='Display string of the reported entry', max_length=255)),
                ('description', models.TextField(help_text='Description of the problem')),
                ('reporter_name', models.CharField(blank=True, help_text='Name of the person reporting', max_length=100)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='open', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Data Report',
                'verbose_name_plural': 'Data Reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
